apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sejutacita
  template:
    metadata:
      labels:
        app: sejutacita
    spec:
      containers:
        - name: sejutacita
          image: muhjaury/sejutacita
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: sejutacita
spec:
  selector:
    app: sejutacita
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
